#!/bin/bash
# description: Description comes here....


start() {
    # code to start app comes here
    # example: daemon program_name &
    pid=$(ps -ef | grep "netvue_recording_rcvr_script1" | grep -v grep | awk '{ print $2 }')
    if [ -z ${pid} ]; then
        /home/pjmd2/netvue_recording_rcvr_script1 &
    else
        echo "netvue_recording_rcvr_script1 already running"
    fi
}

stop() {
    # code to stop app comes here
    # example: killproc program_name
    pid=$(ps -ef | grep "netvue_recording_rcvr_script1" | grep -v grep | awk '{ print $2 }')
    if [ -z ${pid} ]; then echo "netvue_recording_rcvr_script1 already dead"; else kill -9 $pid; fi
    pidnc=$(ps -ef | grep "nc -l -p 8556" | grep -v grep | awk '{ print $2 }')
    if [ -z ${pidnc} ]; then echo "nc for xfr already dead"; else kill -9 $pidnc; fi
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here
       # example: status program_name
       state=$(ps -ef | grep "netvue_recording_rcvr_script1" | grep -v grep)
       if [ -z "$state" ]
       then
          echo "netvue_status_service1 not running"
       else
          echo "netvue_status_service1 is running"
       fi
       exit $?
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
