#!/bin/bash

while true
do
dt=$(date +"%H%M%S")
nc -l -p 8557 | dd bs=16M of=/public/NETVUE_CAM/payload2_$dt.tar
cd /public/NETVUE_CAM
tar xvf /public/NETVUE_CAM/payload2_$dt.tar
rm -f /public/NETVUE_CAM/payload2_$dt.tar
done
